### ISSUE TITLE
Clear database and all downloads

### ISSUE THREAD

**Issue by mrTimay** [tonyofrancis/Fetch#10]
Is there a way to clear the database to allow re-downloads?
Also is there a way to stop and clear all downloads in progress?

**Comment by tonyofrancis** [comment]
@mrTimay The following code allows you to clear all downloads in the database.

```
List<RequestInfo> requests = fetch.get();
        
for (RequestInfo request : requests) {
    fetch.remove(request.getId());
}
```

Fetch downloads one request at a time. If you want to delete the current downloading request you can do something like this.
```
List<RequestInfo> downloadingRequests = fetch.getByStatus(Fetch.STATUS_DOWNLOADING);

for (RequestInfo downloadingRequest : downloadingRequests) { 
    fetch.pause(downloadingRequest.getId());
    //or
    // fetch.remove(downloadingRequest.getId());
}
```

I may implement a removeAll() method in the next version release. I did not add one because I did not want users of the API using it loosely being that everything gets deleted.
