### ISSUE TITLE
Delete Function not working

### ISSUE THREAD

**Issue by Moeinh77** [tonyofrancis/Fetch#152]
Hey,i was using deleteAll() function for deleting all my downloaded files but it seams it doesn't delete them from storage it says that  Cleared Database Main.db but when i check the storage files are still there can you check this to see whats the problem?

**Comment by tonyofrancis** [comment]
@Moeinh77 Just tested the deleteAll() method and all the requests and downloaded files were deleted off the devices. Make sure that M+ devices have accepted the read/write permission before deleting. Fetch is not able to delete files if the permission is not granted. If that's not the case. Where in your code are you calling the delete method?.

**Comment by Moeinh77** [comment]
This is my code 
i make an ob ject from this class and ido my things with it but wheni call deleteAllFiles the deleteAll function doesnt do the job i wonder why

`
class download_controller(val activity: Activity) {

    var UriList=ArrayList<Uri>()

    private var RequestList=ArrayList<Request>()

    private val okHttpClient = OkHttpClient.Builder().build()

    private var GroupmainFetch:Fetch

    private val fetchListener = object : FetchListener {

        override fun onQueued(download: Download) {
            Log.v("Queued",download.tag.toString()+"queued")
        }

        override fun onCompleted(download: Download) {

            Log.v("Completed",download.tag.toString()+"completed")

            UriList.add(Uri.parse(download.file))

            Log.v("Added to List",download.tag.toString()+"added to uri list")

        }

        override fun onError(download: Download) {

    

            Toast.makeText(activity,download.file+
                    "  Error downloading file: "+download.file
                    , Toast.LENGTH_SHORT).show()
        }

        override fun onProgress(download: Download, etaInMilliSeconds: Long, downloadedBytesPerSecond: Long) {

            val progress = download.progress
            Log.d("Fetch", download.tag.toString() + " Progress Completed :" + progress)
        }


        override fun onDeleted(download: Download) {

            Log.v("Deleted!!!",download.file)

        }
    }

//-------------------------------------------------------

    init {
        GroupmainFetch= Fetch.Builder(activity, "Main")
                .setDownloader(OkHttpDownloader(okHttpClient))
                .setDownloadConcurrentLimit(1) 
                .enableLogging(true)
                .addRequestOptions(RequestOptions.AUTO_REMOVE_ON_COMPLETED)
                .build()
        GroupmainFetch.addListener(fetchListener)

    }

    fun addRequest(url:String,tag:String){

        val download_address=Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString()

        val request= Request(url,download_address +"/"+tag)
        request.tag=tag

        RequestList.add(request)

        Log.v("Request",tag+" added to requests!!!")
    }

    fun startDownload(){

        GroupmainFetch.enqueue(RequestList
                , object : Func<List<Download>> {
            override fun call(t: List<Download>) {

                UriList.add(Uri.parse(t.get(0).file))
                UriList.add(Uri.parse(t.get(1).file))

                Toast.makeText(activity,
                        "Started the list download",
                        Toast.LENGTH_SHORT).show()

            }
        }, object : Func<Error> {
            override fun call(t: Error) {
                Toast.makeText(activity,
                        "Error in list download"+t.toString(),
                        Toast.LENGTH_SHORT).show()            }
        })


    }

    fun getDownlodedList():ArrayList<Uri>{

        return UriList

    }

    fun deleteAllFiles(){



        GroupmainFetch.deleteAll()
        GroupmainFetch.close()

        UriList.clear()

    }

    fun closeFetch(){

        GroupmainFetch.close()

    }

}`

**Comment by tonyofrancis** [comment]
@Moeinh77 the reason why the delete all method is not working is because of the `RequestOptions.AUTO_REMOVE_ON_COMPLETED` that is set. This option removes the request inside Fetch but does not delete the file. See the java docs. When `deleteAll()` method is called, the request is not found so the download cannot be deleted. You may want to try one of the other Enqueue RequestOptions.

**Comment by Moeinh77** [comment]
ah,understood
is there a way to be able to redownload files with same name but being able too delete them with fetch functions too?

**Comment by vivekAtHorizon** [comment]
@tonyofrancis

Thank you for the great repo, it's amazing, but I have a situation right now and hope it can be resolved.
So, I have a list of videos to download, but little different than your demo app, in the demo app, as soon as you enter in list activity, all the downloads will start automatically, but in my app, I have to start download when I click on the download button and then the next case is my issue: I started 1st download and then 2nd and 2nd will be added in queue, if I cancel 1st download then 2nd will start to download automatically which is expected behavior. but if I follow the same steps to start downloads but instead of 1st, I canceled 2nd download using `fetch.delete(id)`, then it's not working, what can be an issue? I'm also managing a list of positions that are added to the download and it's working fine when removing the download from the list, the list is updating but somehow `fetch.delete()` is not working (In the start I thought it was a feature that we can't cancel/delete a download that is in the queue, but I think that's not correct.)

Please revert back and help me out with this issue, Thank You!!
