### ISSUE TITLE
Support for chunk download

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#194]
Could fetch add support for chunk download.. 
for example i made a request to download a file and it returned the response below

Transfer-Encoding: chunked
Access-Control-Allow-Origin: https://render.githubusercontent.com
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Strict-Transport-Security: max-age=31536000
Vary: Authorization,Accept-Encoding
 X-Content-Type-Options: nosniff
 X-Frame-Options: deny
 X-XSS-Protection: 1; mode=block
 ETag: "3a6d8172b8fa7e514a4edb16a3ed2c65fc85d0e0"
 Content-Type: application/zip
 Content-Disposition: attachment; filename=Android-Flag-quiz-master.zip

fetch will fail to download such files as it only explicitly supports downloads with content lenght. so adding support for chunked download will be a good idea

**Comment by tonyofrancis** [comment]
looking into this.

**Comment by tonyofrancis** [comment]
@duncanokeyo Just published Fetch 2.2.0-RC1. The Parallel Downloader does not support the chucked encoding type. The sequential Downloader should. The downloader now has a method
`fun getRequestFileDownloaderType(request: ServerRequest, supportedFileDownloaderTypes: Set<Downloader.FileDownloaderType>): FileDownloaderType` that passes in a set of supported download file types. changelog in this version is huge so please review.

**Comment by jpvs0101** [comment]
The sequential downloader seems like NOT supporting Transfer-Encoding: chunked.
Downloaded some unrelated html instead of mp3 file.

Link: https://hindugodsongs.in/

 final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .setDownloadConcurrentLimit(3)
                .enableAutoStart(false)
                .setProgressReportingInterval(1100)
                .setHttpDownloader(new HttpUrlConnectionDownloader(Downloader.FileDownloaderType.SEQUENTIAL)) // Note: Use Downloader.FileDownloaderType.SEQUENTIAL, if you user PARALLEL, resume not working properly
                .build();
        Fetch.Impl.setDefaultInstanceConfiguration(fetchConfiguration);
        



D/LibGlobalFetchLib: Enqueued download DownloadInfo(id=-1786947277, namespace='LibGlobalFetchLib', url='https://hindugodsongs.in/get/download/shani-gayatri-mantra-[hindugodsongs.in].mp3', file='content://com.android.providers.downloads.documents/document/73', group=0, priority=HIGH, headers={Cookie=__cfduid=d22766a6f223a771943be99db82f7db1d1543158628, User-Agent=Mozilla/5.0 (Linux; Android 8.1.0; Redmi 2 Build/OPM7.181005.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.98 Mobile Safari/537.36}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1543163829063, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={"KEY_DOWNLOAD_SUPPORTS_RESUME":"false","KEY_DOWNLOAD_FILE_NAME":"shani-gayatri-mantra-[hindugodsongs.in].mp3 (1)","KEY_DOWNLOAD_USER_AGENT":"Mozilla\/5.0 (Linux; Android 8.1.0; Redmi 2 Build\/OPM7.181005.003; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/61.0.3163.98 Mobile Safari\/537.36","KEY_DOWNLOAD_SAVE_PATH":"content:\/\/com.android.providers.downloads.documents\/document\/73"})
D/LibGlobalFetchLib: PriorityIterator backoffTime reset to 500 milliseconds
D/LibGlobalFetchLib: PriorityIterator started
D/LibGlobalFetchLib: PriorityIterator backoffTime reset to 500 milliseconds
D/LibGlobalFetchLib: Added DownloadInfo(id=-1786947277, namespace='LibGlobalFetchLib', url='https://hindugodsongs.in/get/download/shani-gayatri-mantra-[hindugodsongs.in].mp3', file='content://com.android.providers.downloads.documents/document/73', group=0, priority=HIGH, headers={Cookie=__cfduid=d22766a6f223a771943be99db82f7db1d1543158628, User-Agent=Mozilla/5.0 (Linux; Android 8.1.0; Redmi 2 Build/OPM7.181005.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.98 Mobile Safari/537.36}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1543163829063, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={"KEY_DOWNLOAD_SUPPORTS_RESUME":"false","KEY_DOWNLOAD_FILE_NAME":"shani-gayatri-mantra-[hindugodsongs.in].mp3 (1)","KEY_DOWNLOAD_USER_AGENT":"Mozilla\/5.0 (Linux; Android 8.1.0; Redmi 2 Build\/OPM7.181005.003; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/61.0.3163.98 Mobile Safari\/537.36","KEY_DOWNLOAD_SAVE_PATH":"content:\/\/com.android.providers.downloads.documents\/document\/73"})
D/LibGlobalFetchLib: Queued DownloadInfo(id=-1786947277, namespace='LibGlobalFetchLib', url='https://hindugodsongs.in/get/download/shani-gayatri-mantra-[hindugodsongs.in].mp3', file='content://com.android.providers.downloads.documents/document/73', group=0, priority=HIGH, headers={Cookie=__cfduid=d22766a6f223a771943be99db82f7db1d1543158628, User-Agent=Mozilla/5.0 (Linux; Android 8.1.0; Redmi 2 Build/OPM7.181005.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.98 Mobile Safari/537.36}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1543163829063, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={"KEY_DOWNLOAD_SUPPORTS_RESUME":"false","KEY_DOWNLOAD_FILE_NAME":"shani-gayatri-mantra-[hindugodsongs.in].mp3 (1)","KEY_DOWNLOAD_USER_AGENT":"Mozilla\/5.0 (Linux; Android 8.1.0; Redmi 2 Build\/OPM7.181005.003; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/61.0.3163.98 Mobile Safari\/537.36","KEY_DOWNLOAD_SAVE_PATH":"content:\/\/com.android.providers.downloads.documents\/document\/73"}) for download
D/LibGlobalFetchLib: DownloadManager starting download DownloadInfo(id=-1786947277, namespace='LibGlobalFetchLib', url='https://hindugodsongs.in/get/download/shani-gayatri-mantra-[hindugodsongs.in].mp3', file='content://com.android.providers.downloads.documents/document/73', group=0, priority=HIGH, headers={Cookie=__cfduid=d22766a6f223a771943be99db82f7db1d1543158628, User-Agent=Mozilla/5.0 (Linux; Android 8.1.0; Redmi 2 Build/OPM7.181005.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.98 Mobile Safari/537.36}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1543163829063, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={"KEY_DOWNLOAD_SUPPORTS_RESUME":"false","KEY_DOWNLOAD_FILE_NAME":"shani-gayatri-mantra-[hindugodsongs.in].mp3 (1)","KEY_DOWNLOAD_USER_AGENT":"Mozilla\/5.0 (Linux; Android 8.1.0; Redmi 2 Build\/OPM7.181005.003; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/61.0.3163.98 Mobile Safari\/537.36","KEY_DOWNLOAD_SAVE_PATH":"content:\/\/com.android.providers.downloads.documents\/document\/73"})
D/LibGlobalFetchLib: FileDownloader starting Download DownloadInfo(id=-1786947277, namespace='LibGlobalFetchLib', url='https://hindugodsongs.in/get/download/shani-gayatri-mantra-[hindugodsongs.in].mp3', file='content://com.android.providers.downloads.documents/document/73', group=0, priority=HIGH, headers={Cookie=__cfduid=d22766a6f223a771943be99db82f7db1d1543158628, User-Agent=Mozilla/5.0 (Linux; Android 8.1.0; Redmi 2 Build/OPM7.181005.003; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/61.0.3163.98 Mobile Safari/537.36}, downloaded=0, total=-1, status=QUEUED, error=NONE, networkType=ALL, created=1543163829063, tag=null, enqueueAction=UPDATE_ACCORDINGLY, identifier=0, downloadOnEnqueue=true, extras={"KEY_DOWNLOAD_SUPPORTS_RESUME":"false","KEY_DOWNLOAD_FILE_NAME":"shani-gayatri-mantra-[hindugodsongs.in].mp3 (1)","KEY_DOWNLOAD_USER_AGENT":"Mozilla\/5.0 (Linux; Android 8.1.0; Redmi 2 Build\/OPM7.181005.003; wv) AppleWebKit\/537.36 (KHTML, like Gecko) Version\/4.0 Chrome\/61.0.3163.98 Mobile Safari\/537.36","KEY_DOWNLOAD_SAVE_PATH":"content:\/\/com.android.providers.downloads.documents\/document\/73"})
W/OkHttpClient: A connection to https://hindugodsongs.in/ was leaked. Did you forget to close a response body?
D/LibGlobalFetchLib: PriorityIterator backoffTime reset to 500 milliseconds
