### ISSUE TITLE
Accurate error reporting

### ISSUE THREAD

**Issue by duncanokeyo** [tonyofrancis/Fetch#199]
https://github.com/tonyofrancis/Fetch/blob/d466c72359ffaf32330734890956490b0a7a63e3/fetch2okhttp/src/main/java/com/tonyodev/fetch2okhttp/OkHttpDownloader.kt#L41

Fetch should be able to capture errors in execute method and report to the user, for example, execute method will throw connection timeout, or other errors okhttp throws, but instead fetch shows Unkown IO error, which does not accurately describe the problem..

**Comment by tonyofrancis** [comment]
@duncanokeyo looking into this

**Comment by tonyofrancis** [comment]
@duncanokeyo when an exception is thrown whiles downloading, Fetch returns the throwable in the error when `onError(download)` method is called on the FetchListeners. To get the error call
`download.getError().getThrowable()`. Note that the `throwable` may be `null`. 

What I will do for the next release is return the error and `throwable` in the` onError` parameter so that it is more apparent.

**Comment by tonyofrancis** [comment]
Just released fetch 2.2.0-RC2 with a few fixes. You should now be able to get the throwable from error class instances. eg: `error.getThrowable()`. Note that the throwable may be null. Methods have been updated on the FetchListener. See change log.
