### ISSUE TITLE
How to remove task, but remain file downloaded

### ISSUE THREAD

**Issue by sough** [tonyofrancis/Fetch#27]
I count number of files currently downloading and if 1 of them is done, i call fetch.get().size() to update count. But that size remains the same and fetch.remove(id) deletes downloaded file eather. Something like removeTask(id) possible?

**Comment by tonyofrancis** [comment]
@sough The `fetch.get()` method returns all request that are managed by the FetchService. One of the reasons why the `fetch.remove(id)` method deletes both the request and the file is because Fetch needs to keep track of downloads so that it does not override files on the file system that are not tired to a specific request. Say for example we have a request pointing to a file and another request pointing to that same file. Fetch needs to track this to prevent both requests from accessing that file or causing data corruption. 

If you need to track different requests based on status, you can use the `Fetch.getByStatus(Fetch.STATUS)` method to get all request of a specific status. You can also call this method inside of a FetchListener for better accuracy if you have current downloads processing.
Let me know if this help.

**Comment by sough** [comment]
Thx, that solves my issue
