### ISSUE TITLE
java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.

### ISSUE THREAD

**Issue by jpvs0101** [tonyofrancis/Fetch#288]
1) Goto kproxy.com
2) Enter www.yts.am
3) Now try to download any torrent from it using Fetch.
It failed due to certificate error.

Refer this: https://github.com/smanikandan14/ThinDownloadManager/issues/107

It would be great if you solved this ASAP. Also please do a comprehensive test of downloadable links. For example blob links, Base64 data links, relative links, magnet links, etc. We just need like " Give a link to Fetch, done!". 

I love this lib.
Fetch should be the best of best!

**Comment by tonyofrancis** [comment]
@jpvs0101 Because each app has different security requirements when it comes to certificates, the library cannot just create a default trust manager/ssl factory. This may expose other security risk concerning certificates.  In fetch 2.3.2 The Downloader interface now has a new method `onPreExecute` that lets you configure the HttpsurlConnection with your trust manager, etc before it executes/connects.

```java
  final FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
                .enableRetryOnNetworkGain(true)
                .setDownloadConcurrentLimit(3)
                .setHttpDownloader(new HttpsUrlConnectionDownloader(Downloader.FileDownloaderType.PARALLEL))
                .build();


  public class HttpsUrlConnectionDownloader extends HttpUrlConnectionDownloader {

        public HttpsUrlConnectionDownloader(@NotNull Downloader.FileDownloaderType fileDownloaderType) {
            super(fileDownloaderType);
        }

        @Override
        public void onPreClientExecute(@NotNull HttpURLConnection client, @NotNull Downloader.ServerRequest request) {
            super.onPreClientExecute(client, request);
            if (request.getUrl().startsWith("https")) {
                HttpsURLConnection httpsURLConnection = (HttpsURLConnection) client;
                httpsURLConnection.setSSLSocketFactory(getSSLSocketFactory());
            }
        }

        private SSLSocketFactory getSSLSocketFactory() {
            SSLContext sslContext = null;
            try {
                TrustManager[] tm = {
                        new X509TrustManager() {
                            @Override
                            public void checkClientTrusted(X509Certificate[] chain, String authType) throws CertificateException {}
                            @Override
                            public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException {}
                            @Override
                            public X509Certificate[] getAcceptedIssuers() { return null; }
                        }
                };
                sslContext = SSLContext.getInstance("SSL");
                sslContext.init(null, tm, null);
                HttpsURLConnection.setDefaultHostnameVerifier(new HostnameVerifier() {
                    @Override
                    public boolean verify(String hostname, SSLSession session) {
                        return true;
                    }
                });
            } catch(Exception e) {
                e.printStackTrace();
            }
            return sslContext.getSocketFactory();
        }

    }
```

**Comment by jpvs0101** [comment]
I will test, honestly i don't know much about this stuff, so can you give
an default in built option with the above code. So we can just call, like
'handleCertificate()' in fetch config. We can avoid write code again and
again for simple apps.

**Comment by tonyofrancis** [comment]
@jpvs0101 According to the Android the android documentation [here](https://developer.android.com/training/articles/security-ssl]) it is unsafe to do so. Better that a developer handles this on an app by app basis.

_Caution: Many web sites describe a poor alternative solution which is to install a TrustManager that does nothing. If you do this you might as well not be encrypting your communication, because anyone can attack your users at a public Wi-Fi hotspot by using DNS tricks to send your users' traffic through a proxy of their own that pretends to be your server. The attacker can then record passwords and other personal data. This works because the attacker can generate a certificate and—without a TrustManager that actually validates that the certificate comes from a trusted source—your app could be talking to anyone. So don't do this, not even temporarily. You can always make your app trust the issuer of the server's certificate, so just do it._

Being that I know very little on certificates and protocol security, I will not implement a default solution and leave this up the developer/app.

Best!

**Comment by jpvs0101** [comment]
Hope, someone will contribute on this...

**Comment by jpvs0101** [comment]
Hi,
I tested ADM app, it downloads the same link without any issues, so there
should be possibilities without compromising security, so say if we
implement download manager using your library, it is important to implement
this. Hope you understand that. If you have time just dig through it, like
I said this library will be one stop shop!

**Comment by jpvs0101** [comment]
Seems like working with V2.3.4

final OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .readTimeout(20, TimeUnit.SECONDS) //increase read timeout as needed
                .connectTimeout(20, TimeUnit.SECONDS) //increase connection timeout as needed
                .followRedirects(true)
                .followSslRedirects(true)
                .build();
        return new OkHttpDownloader(okHttpClient,
                Downloader.FileDownloaderType.PARALLEL);

Great job Iron Man... ;)
