### ISSUE TITLE
Question: Cache file as multiple parts

### ISSUE THREAD

**Issue by jpvs0101** [tonyofrancis/Fetch#291]
In `Downloader.FileDownloaderType.PARALLEL` mode, I have seen that fetch uses app's internal storage to cache the parts of the download file while downloading. But the app's internal storage usage is limited, so,

1) In `Downloader.FileDownloaderType.PARALLEL` mode t it create issues when downloading large file (say a 4GB file) ? 
2) If yes, what is the best practice?
3) Is the same caching method used for `Downloader.FileDownloaderType.SEQUENTIAL` mode?

**Comment by tonyofrancis** [comment]
1. By default Fetch caches to the internal storage and will only create 7 temp files for any download over 1 GB and 5 or less temp files for any download under 1GB unless you change the default FileSlicingCount via the downloader by overriding the `getFileSlicingCount(request: ServerRequest, contentLength: Long): Int` method. These temp files only store a single long value(8bytes) that tells Fetch where to resume a download slice in Parallel mode. **Note that these temp files are not stored in the apps cache directory because the Android OS is able to delete those files at will and will cause an incomplete download to start from the beginning.**
2. Fetch will clean up those temp files after a download completes or the download/request is delete or invalid in the Fetch database. The library does a great job at cleaning up those files. If you would like to change the directory that these files are stored in, you will need to provide the Fetch configuration a custom StorageResolver and override the `getDirectoryForFileDownloaderTypeParallel(request: Downloader.ServerRequest): String` method
3. The Sequential mode does not use temp files. All data is stored directly in the database.

**Comment by jpvs0101** [comment]
So no matter what, the actual downloaded data always will be directly
stored on the location we select right?

I thought that the data will be stored on the slice files, for example,

- We initiate a 100MB download location X
- Fetch creates 5 x 20 MB file in internal storage
- After download finished, it will be merged and moved to location X

To be confirm, the actual usage of slices is only to store resume points,
not downloaded data, right?

**Comment by jpvs0101** [comment]
Great!
