### ISSUE TITLE
DownloadId 

### ISSUE THREAD

**Issue by HassanRaza1112** [tonyofrancis/Fetch#3]
My downloadId = -1 what is the reason please help me asap .

```
Fetch fetch = Fetch.getInstance(MainActivity.this);
Request request = new Request("http://androhub.com/demo/demo.mp4", Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString();

final long downloadId = fetch.enqueue(request);

fetch.addFetchListener(new FetchListener() {
            @Override
            public void onUpdate(long id, int status, int progress, int error) {
                if(downloadId== id){
                    progressDialog.setProgress(progress);
                    Log.d("TAG",String.valueOf(progress));
                    if(progress>=100){
                        progressDialog.dismiss();
                    }
                }

            }
});

//Log.d("TAG",fetch.getFilePath(downloadId).toString());
fetch.release();

**Comment by tonyofrancis** [comment]
The reasons why you may be getting an ID of -1 when enqueuing could be the following:

1. Fetch could not enqueue your request because the device ran out of space.
2. Fetch already contains this request. A request with the same downloaded file path already exist and is managed by Fetch. **Fetch does not override local files.** 
3. The file you want to download/enqueue is already located in the directory you wish to save it in.

For the example you provided above, you seem to be creating multiple requests with the same destination file path which is actually a directory and not a unique file. **Each new request should have a unique file path**.Your request should be similar to the following.

```
String url = "http://androhub.com/demo/demo.mp4";
String filePath = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString()
+ "/demo.mp4";

Request request = new Request(url,filePath);
long download id = fetch.enqueue(request);
```
A great way to generate unique file paths is to add the date or time to the file name/path.
```
String dateString = new Date().toString();

String filePath = Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString()
+ "/" + dateString + "_demo.mp4";
```

**Comment by HassanRaza1112** [comment]
OK got it , but how can I check if the file already exists or not ?

On Feb 16, 2017 10:15 PM, "Tonyo Francis" <notifications@github.com> wrote:

The reasons why you may be getting an ID of -1 when enqueuing could be the
following:

   1. Fetch could not enqueue your request because the device ran out of
   space.
   2. Fetch already contains this request. A request with the same
   downloaded file path already exist and is managed by Fetch. *Fetch does
   not override local files.*
   3. The file you want to download/enqueue is already located in the
   directory you wish to save it in.

For the example you provided above, you seem to be creating multiple
requests with the same destination file path which is actually a directory
and not a unique file. *Each new request should have a unique file path*.Your
request should be similar to the following.

String url = "http://androhub.com/demo/demo.mp4";
String filePath =
Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString()
+ "/demo.mp4";

Request request = new Request(url,filePath);
long download id = fetch.enqueue(request);

A great way to generate unique file paths is to add the date or time to the
file name/path.

String dateString = new Date().toString();

String filePath =
Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS).toString()
+ "/" + dateString + "_demo.mp4";

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/tonyofrancis/Fetch/issues/3#issuecomment-280395654>,
or mute
the thread
