### ISSUE TITLE
How does Fetch notifty the app about file already present

### ISSUE THREAD

**Issue by raju249** [tonyofrancis/Fetch#31]
Hi @tonyofrancis ,

I want that my app should be notified by fetch if the requested file already exists.
I tried in the listener to get it notified, but couldn't.

I used ```Fetch.ERROR_ENQUEUE_ERROR``` and ```Fetch.ERROR_FILE_ALREADY_CREATED``` but couldn't get any response from fetch.

Any idea ?

Thanks,

**Comment by tonyofrancis** [comment]
@raju249 If a request already exist, when enqueuing a request into Fetch, Fetch will return -1 as the id which means that the request could not be enqueued because it is already in the database.
```java
Request request = new Request("sample.txt");
long downloadId = fetch.enqueue(request);

if(downloadId == -1) {
  //The request was not queued because a request already exist.
}
```

## Advanced
You can use `Fetch.ERROR_ENQUEUE_ERROR` and `Fetch.ERROR_FILE_ALREADY_CREATED` if you are working **directly** with the FetchService. You can used the FetchService directly if you want to create your own Manager and not use Fetch. You can look at the project source code and see how Fetch sends messages to the FetchService.

**Comment by raju249** [comment]
Great, Thanks @tonyofrancis 
Once again @tonyofrancis , this is the most awesome down-loader library I have seen for android.
🙌 🙌 Hats off.

Closing this issue, and my problem was that I didn't know that ```id``` is ```-1``` for enqueue error. 😄
