### ISSUE TITLE
Fetch close not working

### ISSUE THREAD

**Issue by munix** [tonyofrancis/Fetch#337]
When I use 
Fetch.Impl.getDefaultInstance().close();
Log.v( Constants.TAG, "Close Fetch instance" );

Log.v( Constants.TAG, "Fetch instance is closed? " + Fetch.Impl.getDefaultInstance().isClosed() );

Fetch.Impl.getDefaultInstance().isClosed() get false every time. Obviously first of all I have initialized the Fetch instance.

**Comment by tonyofrancis** [comment]
@munix Notice what you are doing.
You get a default instance of Fetch through `Fetch.Impl.getDefaultInstance()` and the call close on it.
And then again call `Fetch.Impl.getDefaultInstance()` to check if it is closed. Every time you call `Fetch.Impl.getDefaultInstance()` if the instance is closed that method will create a new default instance as it suppose to because you called getDefault instance. Hope this helps.

**Comment by munix** [comment]
Oh my!! Sorry. I'm an idiot!
