### ISSUE TITLE
issue in content length

### ISSUE THREAD

**Issue by anshupatel25** [tonyofrancis/Fetch#375]
hello,
i am developing one application that have multiple file downloading functionality, and i am integrated fetch library for user can easily download large file even if user have slow network.

but issue is when i am downloading file CONTENT-LENGTH value return should be -1 i don't know whats the problem and that file i downloaded from browser also it work perfectly fine. but that library return -1 

so please let me know if this library have manually add content length feature ?? or any solution for this

**Comment by tonyofrancis** [comment]
@anshupatel25 Does the file download fine with Fetch?. The library may return -1 for the content-length because that is what the server returned. It may simply just mean that the files length is not know(undetermined). Fetch is still able to download files even if the content length is not determined. Resume is not supported for if the server returns -1 for the content length. Hope this helps.
