### ISSUE TITLE
Crash at Fetch.Impl.getDefaultInstance();

### ISSUE THREAD

**Issue by yohane55** [tonyofrancis/Fetch#382]
I was trying to initialize fetch default configuration in different thread and on main thread when trying to get default instance i some times get app crashes due race condition I think.

so just to avoid the app crashes it would be great to have default configuration which is an optimal for most case and used when none is provided by the user. This way it would be more crash free.

```
fun getDefaultInstance(): Fetch {
    return synchronized(lock) {
        val fetchConfiguration = defaultFetchConfiguration
                ?: **LIBRARY_DEFAULT_CONFIGURATION**

//throw FetchException(GLOBAL_FETCH_CONFIGURATION_NOT_SET)
        val defaultFetch = defaultFetchInstance
        if (defaultFetch == null || defaultFetch.isClosed) {
            val newDefaultFetch = FetchImpl.newInstance(FetchModulesBuilder.buildModulesFromPrefs(fetchConfiguration))
            defaultFetchInstance = newDefaultFetch
            newDefaultFetch
        } else {
            defaultFetch
        }
    }
}
```

**Comment by tonyofrancis** [comment]
@yohane55 The crash indicates that the global configuration is not set and rightfully so. The reason why this cannot be set initially by the library is because it requires a context to be passed in. The best practice is to always set the default configuration when the app starts in the Application class `onCreate` method.
Hope this helps.

**Comment by yohane55** [comment]
@tonyofrancis  Ok now I get it now. Thanks!
