### ISSUE TITLE
Get Average download complete speed

### ISSUE THREAD

**Issue by maulik9898** [tonyofrancis/Fetch#404]
How can i get Average download speed at which download is complete. It is for completed download to know at which average speed whole download is completed .

**Comment by tonyofrancis** [comment]
@maulik9898 There are many ways to get the average download speed. 
1. From a listener attached to fetch.
2. From the `download.getDownloadedBytesPerSecond()` itself.

See the documentation.

```java
      fetch.addListener(new AbstractFetchListener() {
            @Override
            public void onProgress(@NotNull Download download, long etaInMilliSeconds, long downloadedBytesPerSecond) {
                //the listener returns downloadedBytesPerSecond which is the average downloaded bytes per second.
                long averageBytesPerSecond = download.getDownloadedBytesPerSecond(); // also returns the same value

            }
        });
```

**Comment by maulik9898** [comment]
I was talking about overall download speed after download is completed.
Because after download is completed speed become -1 so instead of this i was hoping that i can get overall average speed of completed download

**Comment by tonyofrancis** [comment]
@maulik9898 After a download completes, the `getDownloadedBytesPerSecond` field is set to -1 because it is no longer being downloaded. No point in the library saving this information. What you can do is keep a map of the returned getDownloadedBytesPerSecond and store that data somewhere for each download. After the download is done you can then calculate the average.

Fetch also has a class called `AverageCalculator` that you can use to store/calculate the average download speed per download.

Hope this helps.

PS: If you need to persist this data. You can update the download's extras field and save it via `replaceExtras(id: Int, extras: Extras, func: Func<Download>? = null, func2: Func<Error>? = null)`.
