### ISSUE TITLE
setDownloadConcurrentLimit(1) Not working

### ISSUE THREAD

**Issue by MohammadFneish7** [tonyofrancis/Fetch#443]
This is an old/new bug as I believe, where **setDownloadConcurrentLimit(1)** never worked for me. First I thought that it is not working when trying to change it after `Fetch `object is created, but it seems that it is not working even when building with `FetchConfiguration `object. Simply it never worked.

Here is how I'm building Fetch:

```
        FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(context)
                .setDownloadConcurrentLimit(SettingsActivity.getConcurrentLimit())
                .enableRetryOnNetworkGain(true)
                .enableAutoStart(false)
                .setAutoRetryMaxAttempts(3)
                .enableLogging(true)
                .setGlobalNetworkType(SettingsActivity.isWifiOnly() ? NetworkType.WIFI_ONLY : NetworkType.ALL)
                .setNamespace(Constants.NAMESPACE)
                .setNotificationManager(new MyFetchNotificationManager(context) {
                    @NotNull
                    @Override
                    public Fetch getFetchInstanceForNamespace(@NotNull String s) {
                        return fetch;
                    }
                })
                .build();

        fetch = Fetch.Impl.getInstance(fetchConfiguration);
```

And here is where I'm to change after building the Fetch object:

`fetch.setDownloadConcurrentLimit(getConcurrentLimit()); //getConcurrentLimit() will return '1' here`

Thanks

**Comment by tonyofrancis** [comment]
@MohammadFneish7 What happens when you set the setDownloadConcurrentLimit(n) to n numbers. Does fetch download n files or only 1? What version of Fetch are you using? You should be able to test easily with the sample app provided and the DownloadListActivity. Let me know if this helps.

Edit: Just reread your issue. You cannot set concurrent to 1 download? Just tested with the sample app and DownloadListActivity and It works as expected. How many instances of Fetch do you have ongoing?. Could it be that you have more than one instance each downloading 1??

**Comment by MohammadFneish7** [comment]
@tonyofrancis I'm using fetch `com.tonyodev.fetch2:fetch2:3.0.10`. No matter what value I use for `setConcurrentLimit` It keeps downloading every download I pass. Besides, I'm sure that only single instance of fetch is running per application. You can check my application code [here](https://github.com/MohammadFneish7/Casper) or even download and run the apk from [here](https://github.com/MohammadFneish7/Casper/blob/master/app/release/app-release.apk)
