### ISSUE TITLE
How do I check if the download completed in onCreate?

### ISSUE THREAD

**Issue by amoozesh3** [tonyofrancis/Fetch#477]
Hi.
First of all thank you for providing such a nice solution.
How do I check if the download completed in onCreate?
The following code work without problem, but maybe user cancel the download operation before completion and incomplete file exists in the path.

try {
     File root = android.os.Environment.getExternalStorageDirectory();
     File path = new File(root.getAbsolutePath() + "/telavat/" + "shahat.mp3");

     if (path.exists()) {
         dllaye.setVisibility(View.GONE);
     }
 } catch (Exception e) {
 }

How can I understand the download is completed?
I’d appreciate your cooperation.
Thank you & Best Regards,
Ahmad Karimi

**Comment by moisoni97** [comment]
Note: this works only for downloading files in one take, pause/resume won't work because we are deleting the file and the request when the user cancels the download, so everytime it will start from the beginning.

You can check if the files exist in `onCreate` like this:
```
private boolean isFilePresent(String fileName) {
        File root = android.os.Environment.getExternalStorageDirectory();
        File path = new File(root.getAbsolutePath() + "/telavat/" + fileName);
        File file = new File(path);
        return file.exists();
    }
```
Then in `onCreate` check if the file exists:
```
if (isFilePresent("shahat.mp3")) {
            //file exists
        } else {
            //file doesn't exist
        }


```
In order to know when a download has completed, you have to override `onChanged listener`. A little trick I used to avoid incompleted downloaded files is to create a new boolean variable that is true only when `DOWNLOAD_COMPLETED` is triggered, otherwise to delete the file or the request.
```
private boolean isCompleted = false;

 @Override
    public void onChanged(Download download, @NotNull Reason reason) {
        switch (reason) {
            case DOWNLOAD_STARTED:
               
                break;
            case DOWNLOAD_COMPLETED:
                isCompleted = true;
                break;
            case DOWNLOAD_ERROR:
               
                break;
            case DOWNLOAD_WAITING_ON_NETWORK:
               
                break;
            case DOWNLOAD_PROGRESS_CHANGED:
                
                break;
        }
    }
```
On your `Cancel button` (or whenever the user can cancel the download) add this code to delete the incomplete downloaded file:
```
if (!isCompleted && request != null) {
            fetch.delete(request.getId());
        }
```
After all of this the first method which I showed you will only return true if completed downloaded file exists.

**Comment by amoozesh3** [comment]
Hi @moisoni97 .
Thank you very much for your response.
