### ISSUE TITLE
It returns " waitingOnNetwork false " in onQueued method even there is No internetConnection and start download.

### ISSUE THREAD

**Issue by LathiyaVinal** [tonyofrancis/Fetch#485]

**Comment by tonyofrancis** [comment]
When a new download request is enqueued `waitingOnNetwork` returned in `fun onQueued(download: Download, waitingOnNetwork: Boolean)` will always return false because it was just enqueued. After the enqueue process, fetch will try to process and download the enqueued request, if no network is found `onQueued(download: Download, waitingOnNetwork: Boolean)` will be called again with `waitingOnNetwork` as true.
