### ISSUE TITLE
downloaded file getting corrupted if kill app while downloading is in progress.

### ISSUE THREAD

**Issue by LathiyaVinal** [tonyofrancis/Fetch#486]
1)downloaded file getting corrupted if kill app while downloading is in progress.
2) it will be better if you add feature for corrupted file that if kill app or cancel downlaoding then delete corrupted file.

**Comment by tonyofrancis** [comment]
Can you provide a sample to recreate this issue?

**Comment by tonyofrancis** [comment]
@LathiyaVinal This may be related to #419 . I am currently planning for a new version this week with the fixes.

**Comment by tonyofrancis** [comment]
New version of Fetch has been released. See readme for new version number.

**Comment by Dezley-VROwl** [comment]
Hi, this issue is still present for me in 3.0.11. I noticed a few things:

- When you kill the app while it's downloading and then restart the app, it adds the amount of bytes that have been downloaded up to that point to the file. So for example with Big Bunny, the initial file size is 151 MB. If it has downloaded 50 MB and you kill and restart the app, the file size will be set to 201 MB. 

- This breaks the values returned in `OnProgress` in `FetchListener`, because it now calculates the progress based on the 201 MB file size, but still correctly downloads only 151 MB. 

- This in turn causes `OnComplete` to never be called. If you kill and restart the app again at that point, the downloader attempts to download the file again, but this results in a "Request is Unsuccessful" error, probably because it did actually download the amount of bytes it should have downloaded.

- In the case of the Big Bunny video, playback of the video after 151 MB has been downloaded goes fine, despite the wrong file size. This might be specific to video files.

- I think a similar issue occurs when pausing & resuming, but I have not tested that enough to confirm it yet. EDIT: just confirmed this happens with pausing & resuming as well. To see it clearly: let the download progress till ~50%, then pause it and resume it. The progress will fall to somewhere in the 30s and the download finishes at 60/70s. Even no need to kill the app.

I can send you my project and an APK for testing if you need it, but I implemented it in a Unity project so I'm not sure if it will be of any particular help. Let me know if you need it and I'll send it ASAP.

EDIT:
Also I forgot to mention, if you set `preAllocateFileOnCreation` to false, the final file size will be correct, but the `Download` object will still have the incorrect total size.
