### ISSUE TITLE
android 10

### ISSUE THREAD

**Issue by viskum** [tonyofrancis/Fetch#502]
Hey developer,
I an testing this project on android 10 it is not enqueue the download. And not showing any type of updates.(api 28)
But when i test this project on lolipop devices it is working correctly.
can you please tell me what can i do for it.

**Comment by alsojin0806** [comment]
see this link  https://github.com/tonyofrancis/Fetch/issues/463

**Comment by enwokoma** [comment]
@wangjinwei0806 That does not entirely solve the issue. I don't even know why the initial issue was closed... Yes, the download works after the fix but, the underlying issue is that, it doesn't save properly.
Take for instance, after downloading an MP3, that MP3 file is not seen yet by other player apps.

**Comment by viskum** [comment]
Hey...there...
The Issue was fixed by the upper link👍👍👍
