### ISSUE TITLE
Continue Downloading file even after screen lock.

### ISSUE THREAD

**Issue by abhishekhugetech** [tonyofrancis/Fetch#505]
Is there any way to keep the download running even after the user has pressed the lock screen button.

Currently, my device android version is 10 (Pie)

**Comment by thezeeshan92** [comment]
Yes, you can download using foreground service.

**Comment by abhishekhugetech** [comment]
@ZeeshanArid Thanks for the answer but I am already having a foreground service that enqueues the download again and again if the download fails (not canceled by the user). But the problem is that I have to show one extra notification for running that ForegroundService (Maybe, not good for UX). 

Is there any way to make the Download Service Foreground while showing the default notification by the fetch library.

**Comment by tonyofrancis** [comment]
Background downloading is very complex on Android because some device manufacturers force kill your app even when a foreground service is running. Even WorkManager does not always work correctly.

See: https://dontkillmyapp.com/
See: https://issuetracker.google.com/issues/122098785

The best you can do, is to implement a Foreground Service and inform the user to disable any battery settings that may cause the system to kill the app when it is in the background.

If the user disables battery settings, then you can run work manager reliably.

**Comment by abhishekhugetech** [comment]
Thanks, @tonyofrancis It's best if we disable battery optimization for our app, then it works perfectly fine with a foreground service.
