### ISSUE TITLE
Specific fileDownloaderType in HttpUrlConnectionDownloader not working

### ISSUE THREAD

**Issue by carrypann** [tonyofrancis/Fetch#508]
I declare a FetchConfiguration with a HttpUrlConnectionDownloader like this:
```
    FetchConfiguration fetchConfiguration = new FetchConfiguration.Builder(this)
            .setHttpDownloader(new HttpUrlConnectionDownloader(Downloader.FileDownloaderType.PARALLEL))
            .setDownloadConcurrentLimit(3)
            .build();
```

However Fetch still check download type and ignores the fileDownloaderType I specific:
```
    override fun getRequestSupportedFileDownloaderTypes(request: Downloader.ServerRequest): Set<Downloader.FileDownloaderType> {
        return try {
            getRequestSupportedFileDownloaderTypes(request, this)
        } catch (e: Exception) {
            mutableSetOf(fileDownloaderType)
        }
    }
```

Furthermore, `FetchCoreUtils.getRequestSupportedFileDownloaderTypes` has catched generic exception, so above catch block will never be executed. 

```
// FetchCoreUtils
fun getRequestSupportedFileDownloaderTypes(request: Downloader.ServerRequest, downloader: Downloader<*, *>): Set<Downloader.FileDownloaderType> {
    val fileDownloaderTypeSet = mutableSetOf(Downloader.FileDownloaderType.SEQUENTIAL)
    return try {
        val response = downloader.execute(request, object : InterruptMonitor {
            override val isInterrupted: Boolean
                get() = false
        })
        if (response != null) {
            if (isParallelDownloadingSupported(response.responseHeaders)) {
                fileDownloaderTypeSet.add(Downloader.FileDownloaderType.PARALLEL)
            }
            downloader.disconnect(response)
        }
        fileDownloaderTypeSet
    } catch (e: Exception) {
        fileDownloaderTypeSet
    }
}
```

And `GET` HTTP method is used to check if parallel downloading supported, it's a bit rough sometimes because it will cause warning or error in resource server, maybe `HEAD` method is the best choice, but the default is `GET` and can not change by user.

**Comment by tonyofrancis** [comment]
@pop0505 Thanks for using Fetch.

The latest version of Fetch implements `getRequestSupportedFileDownloaderTypes(request: Downloader.ServerRequest): Set<Downloader.FileDownloaderType>` as such:
```java
    override fun getRequestSupportedFileDownloaderTypes(request: Downloader.ServerRequest): Set<Downloader.FileDownloaderType> {
        if (fileDownloaderType == Downloader.FileDownloaderType.SEQUENTIAL) {
            return mutableSetOf(fileDownloaderType)
        }
        return try {
            getRequestSupportedFileDownloaderTypes(request, this)
        } catch (e: Exception) {
            mutableSetOf(fileDownloaderType)
        }
    }
```
A network call is made to the server to verify that the server properly supports range requests / parallel downloading. If `Downloader.FileDownloaderType.SEQUENTIAL` is not specified.

After much testing. The `HEAD` method may not be supported by some servers. In order to provide the best experience the `GET` method is used.

In the next version of Fetch, there will be support for you to change this. All you would have to do is override the downloader method below and return true.
```java
override fun getHeadRequestMethodSupported(request: Downloader.ServerRequest): Boolean {
        return false
    }
```

You can also override `getRequestSupportedFileDownloaderTypes` to return the supported types without doing a network check.
```java
    override fun getRequestSupportedFileDownloaderTypes(request: Downloader.ServerRequest): Set<Downloader.FileDownloaderType> {
       return mutableSetOf(fileDownloaderType)
}
```

**Comment by tonyofrancis** [comment]
New version of Fetch has been released. See readme for new version number.
