### ISSUE TITLE
update issue

### ISSUE THREAD

**Issue by burhanaksendir** [tonyofrancis/Fetch#8]
I'm trying to download a video from a URL:
http://www.sample-videos.com/video/mp4/720/big_buck_bunny_720p_2mb.mp4

progres and fileSize not updating while downloading a file.

D/fetchDebug: id:237955074420,status:901,progress:0,error:-1
I/fetchDebug: id: 237955074420 downloadedBytes: 444171 / fileSize: -1
D/fetchDebug: id:237955074420,status:901,progress:0,error:-1
I/fetchDebug: id: 237955074420 downloadedBytes: 744735 / fileSize: -1
D/fetchDebug: id:237955074420,status:901,progress:0,error:-1
I/fetchDebug: id: 237955074420 downloadedBytes: 1087407 / fileSize: -1
D/fetchDebug: id:237955074420,status:901,progress:0,error:-1
I/fetchDebug: id: 237955074420 downloadedBytes: 1637715 / fileSize: -1
......

**Comment by tonyofrancis** [comment]
@burhanaksendir The request is downloading, but the server did not provide the content-length(file size) of the video for Fetch to determine the percentage progress. This normally happens when the content you want to download is small. What you can do is add a check to your code to determine when progress is 0 and fileSize is -1. This is an indication that the download progress cannot be determined and your UI should be handled undetermined progress according.
