### ISSUE TITLE
multi-task downloads

### ISSUE THREAD

**Issue by burhanaksendir** [tonyofrancis/Fetch#9]
Start another file after it finishes downloading one. How do I start multiple file downloads at the same time?

**Comment by tonyofrancis** [comment]
@burhanaksendir Fetch does not support parallel downloads. In order to provide the best user experience, Fetch runs one download at a time in the background. Each request is queued and processed in the order they were enqueued. Each request enqueued is queued with a priority of **Normal**. If you have a download that needs to be executed as soon as possible, you can enqueue it with a priority of **High**.

```
Request request = new Request(url,filepath);
request.setPriority(Fetch.PRIORITY_HIGH);
fetch.enqueue(request);
```

**Comment by burhanaksendir** [comment]
Thanks
